### ISSUE TITLE
Proxy Error: No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by sam-the-programmer** [deta/space-cli#108]
```
2023/05/13 15:06:20 http: proxy error: dial tcp [::1]:4201: connectex: No connection could be made because the target machine actively refused it.
```

I keep getting this error whenever I use `space dev` to emulate features locally. I'm using version **0.3.5**.

My space file looks like this.

```yaml
v: 0
micros:
  - name: backend
    src: .
    engine: python3.9
    dev: python main.py --local
    primary: true
    public_routes:
      - "/api/*"
      - "/test/coffee"
```

(plus some preset environment variables)

Could it be something to do with the fact that the error includes the port number _4201_ when it's actually running on _4200_
