### ISSUE TITLE
Runtime.ExitError on root path after using `space push`

### ISSUE THREAD

**Issue by diamond-fish** [deta/space-cli#134]
I'm following [this tutorial ](https://fastapi.tiangolo.com/tutorial/), but after `space push` I get the error below even though it works fine locally (via `uvicorn main:app --reload`) and deploys without errors.

https://fastapitutorial-1-j0837537.deta.app/
```
Error Type:
Runtime.ExitError

Error Message:
RequestId: c937c6ec-3304-4dad-8561-73e8116addfe Error: Runtime exited with error: exit status 1

Logs:
time='2023-07-25T23:00:52Z' level=info msg='serving logs listener on sandbox.localdomain:1234' agent=logsApiAgent
TELEMETRY	Name: telemetry-extension	State: Already subscribed	Types: [Function]
Traceback (most recent call last):
File '/opt/python/bin/uvicorn', line 5, in 
from uvicorn.main import main
File '/opt/python/uvicorn/__init__.py', line 1, in 
from uvicorn.config import Config
File '/opt/python/uvicorn/config.py', line 1, in 
import asyncio
File '/var/lang/lib/python3.9/asyncio/__init__.py', line 8, in 
from .base_events import *
File '/var/lang/lib/python3.9/asyncio/base_events.py', line 45, in 
from . import staggered
File '/var/lang/lib/python3.9/asyncio/staggered.py', line 6, in 
import typing
File '/opt/python/typing.py', line 1359, in 
class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
File '/opt/python/typing.py', line 1007, in __new__
self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'
```

**main.py**
```python
from typing import Annotated
from fastapi import FastAPI, Query
from pydantic import BaseModel

class Item(BaseModel):
  name: str
  price: Annotated[float, Query(gt=0)]

app = FastAPI()

@app.get('/')
def get_root():
  return { 'message': 'Hello World' }

@app.post('/items/')
def create_item(item: Item) -> Item:
  return item
```

**requirements.txt**
```
fastapi
pydantic
typing
uvicorn[standard]
```

**Spacefile**
```yaml
# Spacefile Docs: https://go.deta.dev/docs/spacefile/v0
v: 0
micros:
  - name: fastapi-tutorial
    src: ./
    engine: python3.9
    primary: true
    run: uvicorn main:app
    dev: uvicorn main:app --reload
    public_routes:
      - '/*'
```
